import '../../engine/slm/offline_ai_engine.dart';
import 'models/ai_explanation.dart';
import '../../engine/models/risk_level.dart';
import '../../engine/models/scam_category.dart';

class RakshakClient {

  static Future<AiExplanation?> fetchExplanation({
    required String notificationText,
    required ScamCategory category,
    required RiskLevel risk,
    required double confidence,
    required List<String> matchedRules,
  }) async {
    final offlineEngine = OfflineAiEngine();
    final contextData = 'Text: $notificationText. Risk: ${risk.name}. Context rules: ${matchedRules.join(", ")}';
    
    final result = await offlineEngine.generateExplanation(contextData);
    if (result == null) return null;
    
    return AiExplanation(
      simpleExplanation: result,
      reason: 'Locally generated by Rakshak SafeEngine',
      recommendedAction: 'Stay alert and do not click suspicious links.',
      shortSummary: 'Offline Analysis',
    );
  }

  static Future<AiExplanation?> fetchCallExplanation({
    required String phoneNumber,
    required ScamCategory category,
    required RiskLevel risk,
    required double confidence,
    required List<String> matchedRules,
    required int callDuration,
  }) async {
    final offlineEngine = OfflineAiEngine();
    final contextData = 'Call from $phoneNumber. Length $callDuration. Risk: ${risk.name}. Context rules: ${matchedRules.join(", ")}';
    
    final result = await offlineEngine.generateExplanation(contextData);
    if (result == null) return null;
    
    return AiExplanation(
      simpleExplanation: result,
      reason: 'Locally evaluated by Rakshak CallGuardian',
      recommendedAction: 'If suspicious, block the caller immediately.',
      shortSummary: 'Offline Call Analysis',
    );
  }

  static Future<AiExplanation?> fetchUpiExplanation({
    required String merchantName,
    required String transactionType,
    required double amount,
    required ScamCategory category,
    required RiskLevel risk,
    required double confidence,
    required List<String> matchedRules,
  }) async {
    final offlineEngine = OfflineAiEngine();
    final contextData = 'UPI $transactionType from $merchantName for INR $amount. Risk: ${risk.name}. Context rules: ${matchedRules.join(", ")}';
    
    final result = await offlineEngine.generateExplanation(contextData);
    if (result == null) return null;
    
    return AiExplanation(
      simpleExplanation: result,
      reason: 'Locally evaluated by Rakshak UpIDefender',
      recommendedAction: 'Verify the merchant strictly before inputting your UPI PIN.',
      shortSummary: 'Offline UPI Analysis',
    );
  }

  static Future<AiExplanation?> fetchGeneralizedExplanation(String prompt) async {
    final offlineEngine = OfflineAiEngine();
    final result = await offlineEngine.generateExplanation(prompt);
    
    if (result == null) return null;
    
    return AiExplanation(
      simpleExplanation: result,
      reason: 'On-device LLM evaluation complete',
      recommendedAction: 'Exercise standard caution',
      shortSummary: 'General AI Check',
    );
  }

  static Future<AiExplanation?> fetchScanExplanation({
    required String content,
    required String scanType,
    required ScamCategory category,
    required RiskLevel risk,
    required double confidence,
    required List<String> matchedRules,
  }) async {
    final offlineEngine = OfflineAiEngine();
    final contextData = 'Scanned $scanType content: "$content". Risk: ${risk.name}. Context rules: ${matchedRules.join(", ")}';
    
    final result = await offlineEngine.generateExplanation(contextData);
    if (result == null) return null;
    
    return AiExplanation(
      simpleExplanation: result,
      reason: 'Locally generated by Rakshak SafeScan',
      recommendedAction: 'Stay alert and do not open the scanned link if suspicious.',
      shortSummary: 'Offline Scan Analysis',
    );
  }
}
